services:
  db:
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'user123456'
      POSTGRES_DB: 'market'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
